class item():
    def __init__(self):
        self.id: int
        self.name: str
        self.price: int
        self.inTax: bool
        self.reduceTax: bool
        self.stocks: str

class order():
    def __init__(self):
        self.id: int
        self.refNum: int
        self.orderTime: str
        self.orders: str
        self.total: int
        self.inTax: int
        self.outTax: int
        self.recieve: int
        self.changes: int
        self.state: str